### ISSUE TITLE
Rodar fora do Windows

### ISSUE THREAD

**Issue by strikegamer** [JayrAlencar/nesslab-reader-api.js#1]
É possível rodar esta API em máquinas LINUX ou OSX? Fizemos alguns testes, e rodaram somente em máquinas Windows.

Existe alguma alternativa para as dependências do Leitor.exe e da nesslab.reader.api.dll rodarem fora do Windows?

**Comment by jayralencar** [comment]
Não, só funciona no windows

**Comment by strikegamer** [comment]
Obrigado!

**Comment by jayralencar** [comment]
@strikegamer Tente rodar a nova versão 0.2.0 fora do windows. Agora não estou mais usando C#, mas somente JS.

**Comment by strikegamer** [comment]
Opa! Testando já já!

Uma pergunta: Já trabalhou com Readers Intermec e Acura?

Já retorno informando se deu tudo certo!

**Comment by jayralencar** [comment]
Não, nunca trabalhei com esses. Só com nesslab mesmo!

**Comment by strikegamer** [comment]
Desculpe a demora no retorno, mas confirmando, funciona perfeitamente agora fora do Windows. Testei no Linux e no OSX.
